#!/usr/bin/env bash


function app()
{
   local action=$1
   shift
   case "$action" in
     "prepare") prepare $*;;
     "check") check $*;;
     *) echo not found action! $action; exit 1;;
   esac
}

function check()
{
   local flag=$1
   shift
   case "$flag" in
     "ct-ng") 
            echo "CACHE_HIT: $CACHE_HIT"
            export PATH=$PATH:$CTNG_HOME/bin
            echo "CTNG_HOME: $CTNG_HOME"
            echo "PATH: $PATH"
            which ct-ng && echo "::add-path::$CTNG_HOME/bin"
            which ct-ng || echo "::set-env name=CTNG_OK::1"
     ;;
   esac
}

function prepare()
{
   local flag=$1
   shift
   case "$flag" in
     "ct-ng") 
	 set_github_env "CTNG_HOME" "$HOME/.crosstool-ng"
	 set_github_env "CTNG_CACHE_KEY" "crosstool-ng-last"
     ;;
   esac
}

function set_github_env()
{
  if [ $# -eq 2 ]; then
     echo "::set-env name=$1::$2"
  fi
}

app $*
