#!/usr/bin/env bash


function app()
{
   local action=$1
   shift
   case "$action" in
     "prepare") prepare $*;;
     "check") check $*;;
     "judge") judge $*;;
     "compile_prepare") compile_prepare $*;;
     "build_tool") build_tool $*;;
     "install_tool") install_tool $*;;
     "test_tool") test_tool $*;;
     *) echo not found action! $action; exit 1;;
   esac
}

function test_tool()
{
   local flag=$1
   shift
   case "$flag" in
     "ct-ng")
         which ct-ng && ct-ng list-samples
     ;;
   esac
}

function install_tool()
{
   local flag=$1
   shift
   case "$flag" in
     "ct-ng")
	if [ $CTNG_OK -eq 0 ]; then
	  if [ -e "$CTNG_BUILD" ] ; then
	     cd $CTNG_BUILD
             make install -j 4
             add_github_path "$CTNG_HOME/bin"
	  else
	     echo "CTNG_BUILD not exist!"
	     exit 1
	  fi
        else
	  echo "crosstool-ng oK!" 
	fi
     ;;
   esac
}

function build_tool()
{
   local flag=$1
   shift
   case "$flag" in
     "ct-ng")
	if [ $CTNG_OK -eq 0 ]; then
	  if [ -e "$CTNG_REPO" ] ; then
             cd $CTNG_REPO
             ./bootstrap && ./configure --prefix=$CTNG_HOME
	     if [ $? -eq 0 ]; then
                make -j 4
	        set_github_env "CTNG_BUILD" "$(pwd)"
	     else
	        echo "configure failed!"
		./configure --help
		exit 1
	     fi
	  else
	     echo "CTNG_REPO not exist!"
	     exit 1
	  fi
        else
	  echo "crosstool-ng oK!" 
	fi
     ;;
   esac
}

function compile_prepare()
{
   local flag=$1
   shift
   case "$flag" in
     "ct-ng")
	if [ $CTNG_OK -eq 0 ]; then
	  if [ "$CTNG_REPO" != "" ] ; then
             sudo apt install gperf bison flex texinfo gawk libtool libtool-bin libncurses5-dev help2man -y
	  else
	    echo "CTNG_REPO empty!"
	    exit 1
          fi
	else
	  echo "crosstool-ng oK!" 
	fi
     ;;
   esac
}

function judge()
{
   local flag=$1
   shift
   case "$flag" in
     "ct-ng")
	if [ $CTNG_OK -eq 0 ]; then
	   local r="$(pwd)/build/ct_ng"
	   mkdir -p "$r"
           git clone https://github.com/crosstool-ng/crosstool-ng $r -j 4
           set_github_env "CTNG_REPO" "$r"
	else
	   echo "crosstool-ng Ok!"
        fi
     ;;
   esac
}

function check()
{
   local flag=$1
   shift
   case "$flag" in
     "ct-ng") 
	    local is_ok=0
            echo "CACHE_HIT: $CACHE_HIT"
	    if [ "$CACHE_HIT" == "true" ]; then
               export PATH=$PATH:$CTNG_HOME/bin
               which ct-ng > /dev/null 2>&1
               if [ $? -eq 0 ]; then
		  is_ok=1
                  add_github_path "$CTNG_HOME/bin"
	       else
                  echo "ct-ng not exist!"
	       fi
	    else
               echo "ct-ng cache miss!"
	    fi
            set_github_env "CTNG_OK" "$is_ok"
     ;;
   esac
}

function prepare()
{
   local flag=$1
   shift
   case "$flag" in
     "ct-ng") 
	 set_github_env "CTNG_HOME" "$HOME/.crosstool-ng"
	 set_github_env "CTNG_CACHE_KEY" "crosstool-ng-last"
     ;;
   esac
}

function set_github_env()
{
  if [ $# -eq 2 ]; then
     echo "::set-env name=$1::$2"
  fi
}

function add_github_path()
{
  if [ $# -eq 1 ]; then
     echo "::add-path::$1"
  fi
}

app $*
