name: 交叉编译
on: [push]
jobs:
  setup-crosstool-ng:
     name: 准备crosstool-ng环境
     runs-on: ubuntu-latest
     defaults:
        run:
          shell: bash
     env:
        CTNG_HOME: /home/runner/.crosstool-ng
     steps:
       - name: 检查crosstool-ng环境
         shell: bash
         run: |
            echo "::add-path::$CTNG_HOME/bin"
            echo "CTNG_HOME: $CTNG_HOME"
            echo "PATH: $PATH"
            which ct-ng || echo "::set-env name=CTNG_OK::1"
       - name: 检索crosstool-ng仓库
         uses: actions/checkout@v2
         if: env.CTNG_OK == 0
         with:
           repository: crosstool-ng/crosstool-ng
           path: crosstool-ng
       - name: 编译安装crosstool-ng
         shell: bash
         if: env.CTNG_OK == 0
         run: |
            pwd
            ls
            cd crosstool-ng
            ./bootstrap
            ./configure --prefix=$CTNG_HOME
            make -j4
            make install -j4
            which ct-ng && ct-ng list-samples
