name: 交叉编译
on: [push]
jobs:
  prepare-crosstool-ng:
     name: 准备crosstool-ng环境
     runs-on: ubuntu-latest
     defaults:
        run:
          shell: bash
     steps:
       - name: 检索cross仓库
         uses: actions/checkout@v2

       - name: 初始化
         run: ./cross prepare ct-ng

       - name: 检查crosstool-ng缓存
         uses: actions/cache@v1
         id: cache
         with:
            path: ${{ env.CTNG_HOME }}
            key: ${{ runner.os }}-${{ env.CTNG_CACHE_KEY }}

       - name: 检查crosstool-ng环境
         run: ./cross check ct-ng
         env:
           CACHE_HIT: ${{ steps.cache.outputs.cache-hit }}

       - name: 检索crosstool-ng仓库
         uses: actions/checkout@v2
         if: env.CTNG_OK == 0
         with:
           repository: crosstool-ng/crosstool-ng
           path: crosstool-ng

       - name: 准备crosstool-ng编译环境
         if: env.CTNG_OK == 0 && success()
         run: |
            echo skip
                 #sudo apt install gperf bison flex texinfo gawk libtool libncurses5-dev help2man -y

       - name: 编译安装crosstool-ng
         shell: bash
         if: env.CTNG_OK == 0 && success()
         run: |
            pwd
            ls
            cd crosstool-ng
            sudo apt install gperf bison flex texinfo gawk libtool libncurses5-dev help2man -y
            ./bootstrap
            ./configure --prefix=$CTNG_HOME
            make -j4
            make install -j4
            which ct-ng && ct-ng list-samples

       - name: test
         run: |
             pwd
             ls
             exit 1
