name: 交叉编译
on: [push]
jobs:
  prepare-crosstool-ng:
     name: 准备crosstool-ng环境
     runs-on: ubuntu-latest
     defaults:
        run:
          shell: bash
     steps:
       - name: 检索cross仓库
         uses: actions/checkout@v2

       - name: 初始化
         run: ./cross prepare ct-ng

       - name: 检查crosstool-ng缓存
         uses: actions/cache@v1
         id: cache
         with:
            path: ${{ env.CTNG_HOME }}
            key: ${{ runner.os }}-${{ env.CTNG_CACHE_KEY }}

       - name: 检查crosstool-ng环境
         run: ./cross check ct-ng
         env:
           CACHE_HIT: ${{ steps.cache.outputs.cache-hit }}

       - name: 判断crosstool-ng编译
         run: ./cross judge ct-ng

       - name: 准备crosstool-ng编译环境
         run: ./cross compile_prepare ct-ng

       - name: 编译crosstool-ng
         run: ./cross build_tool ct-ng

       - name: 安装crosstool-ng
         run: ./cross install_tool ct-ng

       - name: 测试crosstool-ng环境
         run: ./cross test_tool ct-ng

       - name: 上传文件
         uses: actions/upload-artifact@v1
         with:
           name: ct-ng
           path: $CTNG_HOME

  cross-tool:
     name: 准备交叉编译工具
     needs: prepare-crosstool-ng
     runs-on: ubuntu-latest
     defaults:
        run:
          shell: bash
     steps:
       - name: 检索cross仓库
         uses: actions/checkout@v2

       - name: 初始化
         run: ./cross prepare tool

       - name: 检查交叉编译工具缓存
         uses: actions/cache@v1
         id: cache
         with:
            path: ${{ env.TOOL_HOME }}
            key: ${{ runner.os }}-${{ env.TOOL_CACHE_KEY }}

       - name: 下载ct-ng
         if: steps.cache.outputs.cache-hit != "true"  
         uses: actions/download-artifact@v1
         with:
           name: ct-ng

       - name: test
         run: |
            pwd
            ls
            env
            exit 1
